"""
submit_training_job.py — Submit the bio-risk training job to Azure ML.

Prerequisites:
  pip install azure-ai-ml azure-identity python-dotenv

Usage:
  python submit_training_job.py

The job runs train.py on a remote compute cluster, registers the resulting
model, and prints the registered model name + version.
"""

import os
import argparse
from pathlib import Path

from azure.ai.ml import Input, MLClient, command
from azure.ai.ml.entities import Environment, Model
from azure.core.exceptions import HttpResponseError
from azure.identity import DefaultAzureCredential
from dotenv import load_dotenv

# Prefer workspace settings from .env over stale process/session variables.
load_dotenv(override=True)

SUBSCRIPTION_ID = os.environ["AZURE_ML_SUBSCRIPTION_ID"]
RESOURCE_GROUP = os.environ["AZURE_ML_RESOURCE_GROUP"]
WORKSPACE_NAME = os.environ["AZURE_ML_WORKSPACE_NAME"]

# Name of an existing compute cluster in your Azure ML workspace.
# Create one via portal: Compute → Compute clusters → + New
DEFAULT_COMPUTE_NAME = os.environ.get("AZURE_ML_COMPUTE_NAME")

MODEL_NAME = "bio-risk-classifier"

# Training data lives at <repo>/data/cardio_train.csv.
# Generated by utility_funcs/split_cardio_dataset.py from cardio vascular_dataset.csv.
DEFAULT_TRAIN_DATA = Path(__file__).resolve().parent.parent / "data" / "cardio_train.csv"


def _print_storage_auth_guidance(ml_client: MLClient, exc: Exception) -> None:
    """Print concrete remediation steps for common datastore upload auth failures."""
    print("\n[ERROR] Azure ML could not upload your job code to workspace storage.")
    print("This is a data-plane RBAC issue on the workspace storage account.")

    try:
        ws = ml_client.workspaces.get(WORKSPACE_NAME)
        storage_account_id = getattr(ws, "storage_account", None)
    except Exception:
        storage_account_id = None

    if storage_account_id:
        print(f"Workspace storage account: {storage_account_id}")

    print("\nFix steps:")
    print("1) Grant your current identity the role 'Storage Blob Data Contributor'")
    print("   on the workspace storage account (or narrower scope to default container).")
    print("2) Ensure you also have Azure ML workspace access (e.g., Contributor).")
    print("3) If storage firewall is enabled, allow your client IP or trusted Azure services.")
    print("4) Re-run: python submit_training_job.py")

    if storage_account_id:
        print("\nHelpful command (replace <principal-id>):")
        print(
            "az role assignment create --assignee <principal-id> "
            f"--role \"Storage Blob Data Contributor\" --scope \"{storage_account_id}\""
        )

    print("\nOriginal error details:")
    print(str(exc))


def _validate_compute_target(ml_client: MLClient, compute_name: str) -> None:
    """Fail fast if the target compute is not suitable for remote training jobs."""
    compute = ml_client.compute.get(compute_name)
    compute_type = (
        getattr(compute, "type", None)
        or getattr(compute, "compute_type", None)
        or getattr(compute, "__class__", type(compute)).__name__
    )
    normalized_type = str(compute_type).replace("_", "").replace("-", "").lower()

    if "computeinstance" in normalized_type:
        raise SystemExit(
            "[ERROR] The configured compute target is a compute instance, not a compute cluster.\n"
            f"Current target: {compute_name}\n\n"
            "This script should run on an Azure ML compute cluster so the job can access workspace "
            "storage and run non-interactively. Create or choose a compute cluster, then re-run with:\n"
            "  python submit_training_job.py --compute <cluster-name>\n\n"
            "You can also set AZURE_ML_COMPUTE_NAME in .env for a persistent default."
        )


def main(compute_name: str, data_path: Path) -> None:
    if not data_path.exists():
        raise SystemExit(
            f"[ERROR] Training data not found at {data_path}.\n"
            "Run utility_funcs/split_cardio_dataset.py to generate cardio_train.csv first."
        )

    credential = DefaultAzureCredential()
    ml_client = MLClient(
        credential=credential,
        subscription_id=SUBSCRIPTION_ID,
        resource_group_name=RESOURCE_GROUP,
        workspace_name=WORKSPACE_NAME,
    )

    _validate_compute_target(ml_client, compute_name)

    # Conda-based environment referencing our conda.yaml
    env = Environment(
        name="bio-risk-train-env",
        conda_file=str(Path(__file__).parent / "conda.yaml"),
        image="mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest",
    )

    job = command(
        display_name="cardio-risk-classifier-training",
        code=str(Path(__file__).parent),   # uploads this folder as source
        command=(
            "python train.py "
            "--data ${{inputs.train_data}} "
            "--output_dir ${{outputs.model_output}}"
        ),
        environment=env,
        compute=compute_name,
        inputs={
            "train_data": Input(type="uri_file", path=str(data_path)),
        },
        # Upload output artifacts so model files are available for registration.
        outputs={"model_output": {"type": "uri_folder", "mode": "upload"}},
    )

    print(f"Submitting training job to compute: {compute_name} …")
    try:
        returned_job = ml_client.jobs.create_or_update(job)
    except HttpResponseError as exc:
        error_text = str(exc)
        if (
            "AuthorizationFailure" in error_text
            or "AuthorizationPermissionMismatch" in error_text
            or "not authorized to perform this operation" in error_text
        ):
            _print_storage_auth_guidance(ml_client, exc)
            raise SystemExit(1) from exc
        raise
    print(f"Job submitted. Name: {returned_job.name}")
    print(f"Studio URL: {returned_job.studio_url}")

    # Wait for completion
    print("Waiting for job to complete (this may take several minutes) …")
    ml_client.jobs.stream(returned_job.name)

    # Guard model registration so canceled/failed jobs do not raise misleading output errors.
    final_job = ml_client.jobs.get(returned_job.name)
    final_status = str(getattr(final_job, "status", "Unknown"))
    print(f"Final job status: {final_status}")
    if final_status.lower() != "completed":
        print("Training job did not complete successfully; skipping model registration.")
        return

    # Register the model from the job output
    model = Model(
        name=MODEL_NAME,
        path=f"azureml://jobs/{returned_job.name}/outputs/model_output",
        description="Cardiovascular 10-year CHD risk classifier (XGBoost + median imputer)",
    )
    registered_model = ml_client.models.create_or_update(model)
    print(f"\nModel registered: {registered_model.name} v{registered_model.version}")
    print("Next step: run  python deploy.py")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--compute",
        default=DEFAULT_COMPUTE_NAME,
        help="Azure ML compute cluster name (default: AZURE_ML_COMPUTE_NAME or DemoMLCompute)",
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=DEFAULT_TRAIN_DATA,
        help="Path to cardio_train.csv (default: <repo-root>/cardio_train.csv)",
    )
    args = parser.parse_args()
    main(compute_name=args.compute, data_path=args.data)
